# BCION Lite — runtime image (DEPLOY-3).
#
# Single-stage build: there is no Node build stage here on purpose.
# `app/static/css/app.css` is committed, already-compiled Tailwind output
# (see mk/dev.mk's `css` target for how it is generated) — this image just
# copies it in with the rest of `app/`, it never runs `npx tailwindcss`.
#
# Dependency install is hash-checked against `requirements.lock` (the
# runtime lockfile only — `requirements-dev.lock`'s test/lint tooling never
# ships in this image). That file was generated by `uv pip compile
# --python-platform linux --python-version 3.11 --generate-hashes
# --system-certs -o requirements.lock pyproject.toml` (see its own header)
# and already fully pins every runtime dependency with a hash, so
# `pip install --require-hashes -r requirements.lock` is the whole story —
# no separate constraints.txt is needed on top of it.
#
# The local `app` package itself is installed editable+`--no-deps`, the
# same pattern mk/dev.mk's `install` target uses locally: it is the
# project being built, not a third-party dependency, so it is deliberately
# never in requirements.lock, and `--no-deps` stops pip re-resolving its
# declared dependencies outside the hash-checked step above.
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# Non-root runtime user (CLAUDE.md/docs/SECURITY.md posture: the process
# never needs root once dependencies are installed). Created before the
# app files are copied in so the final chown below is a single pass.
RUN useradd --uid 10001 --create-home --shell /usr/sbin/nologin bcion

# Install runtime dependencies first, from the lockfile alone, so this
# layer only invalidates when requirements.lock actually changes (not on
# every source edit).
COPY requirements.lock ./requirements.lock
RUN pip install --require-hashes -r requirements.lock

# pyproject.toml is needed for the editable install below; app/ is the
# whole application, including the already-compiled
# app/static/css/app.css and the Jinja templates under app/web/templates
# (both are read via paths relative to the working directory at runtime,
# which is why WORKDIR is /app and app/ is copied to /app/app).
COPY pyproject.toml ./pyproject.toml
COPY app ./app
RUN pip install -e . --no-deps

RUN chown -R bcion:bcion /app
USER bcion

EXPOSE 8000

# No curl/wget in the slim base image — a stdlib urllib call avoids
# pulling in an extra package just for the healthcheck. Raises (non-zero
# exit) on anything but a 2xx/3xx response, which is exactly what
# HEALTHCHECK needs; /healthz is deliberately always-200-if-the-process-
# is-up (app/api/health.py), even with no Supabase/AI config at all.
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD ["python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=2)"]

# No --reload (that is `make dev`'s job, not this image's) and
# --proxy-headers so client IP/scheme are trusted from the reverse proxy
# fronting this container in every real deployment.
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
