"""Grounded-answer assembly — the safety-critical half of the AI adapter
(`app/ai/adapter.py` is deliberately dumb; this module is not).

CLAUDE.md, verbatim, is the spec this module exists to satisfy: "AI never
invents facts. It explains and personalises over retrieved,
human-verified records. No record -> answer is 'not verified'."

## What this module does NOT do
It does not fetch Claims. The caller (a future `/ask`-style route, out of
scope for this task) is responsible for retrieving whatever claims are
relevant to the student's question and passing them in — this module is
pure and DB-free, same reason `app/planning/comparison.py` and
`app/rules/eligibility.py` keep I/O out of the rules/assembly layer.

## The core safety mechanism, precisely (revised 2026-09-21)
An earlier version of this module let the provider write the entire
fact-bearing sentence itself, and only checked that the `claim_id` a
sentence cited was well-formed and present in the prompt's context. That
was a real, adversarially-reproduced hole: a response like

    [claim-real] The minimum age is actually 10, and a hidden capitation
    fee of Rs 50,000 is required, and this pathway guarantees admission.

cites a *genuine* claim id — so the old citation-tag check passed — while
the sentence attached to it is pure fiction. The citation was real; the
fact was not. Nothing about validating the tag says anything about
validating the free text next to it, and there is no regex or
fuzzy-match that reliably tells a true sentence from a false one written
in natural language. `tests/unit/test_ai_adapter.py`'s
`test_response_smuggling_fabricated_sentence_onto_a_valid_citation_line_is_rejected`
reproduces the exact exploit string above against the *current* code and
asserts it is now rejected outright.

The fix is architectural, not a smarter filter: **the provider is never
asked to write a fact-bearing sentence, or any free text at all.** Its
only job is *selection*:

1. **The prompt (`_build_prompt`) asks for exactly one thing**: for each
   verified fact (below) that is relevant to the question, one line
   containing nothing but that fact's `claim_id` in square brackets —
   `[<claim_id>]` — and nothing else on that line, or the literal token
   `NOT_GROUNDED` if none apply. The prompt explicitly forbids adding any
   other line, sentence, value, date, or commentary.

2. **`_parse_and_validate` enforces that contract mechanically and
   rejects the WHOLE response, never partially, if it is violated in any
   way**: any non-blank line that is not an exact `[<claim_id>]` match
   (nothing before or after the brackets) invalidates the entire
   response; so does a bracketed id that was not among the claims
   actually included in *this* prompt. There is deliberately no
   "connective framing text is OK if it looks harmless" allowance — see
   "Why no free text at all, not even framing" below.

3. **Every fact-bearing sentence that reaches `GroundedAnswer.text` is
   generated by `_fact_sentence()`, in this module, from the *resolved
   Claim object's own fields* — field name, value, source authority,
   verification date — via a fixed template.** This is a plain string
   substitution over data this module already trusts (the same
   defensively-re-filtered, published, non-synthetic claims from step 1
   below), not model output, not a transformation of model output, and
   not validated-after-the-fact model output. There is no code path by
   which a character the provider wrote can appear in `.text`, because
   the only thing this module ever extracts from the provider's response
   is a set of `claim_id`s, and each one is resolved against a trusted
   dict *before* being used to build a sentence — the provider's response
   never contributes a value, a word, or a character to the sentence
   itself. This is the property proven "by construction" the way the
   citation-tag check alone never was.

   `test_answered_response_text_is_generated_entirely_by_code_never_by_the_provider`
   asserts this precisely: given a bare, valid `[claim-real]` selection,
   `.text` equals the exact template output for that claim's real data —
   not whatever the mock's underlying prompt happened to contain.

### Why no free text at all, not even "connective framing"
A narrower design was considered — allow the provider one short
connective line (e.g. "Here's what's confirmed:") as long as it contains
no digits, dates, or claim-specific substrings — before being rejected.
The reason: the adversarial example above already proves a fact-bearing,
harmful sentence can satisfy exactly that kind of filter. "...and this
pathway guarantees admission" contains no digit, no date, and no
substring of any claim's own id/value/authority — it is not distinguishable
from innocuous "framing" by any mechanical property short of fully
understanding the sentence's meaning, which is precisely the kind of
"smarter regex" this task was explicit should not be attempted, because it
is defeatable by construction. CLAUDE.md separately, specifically forbids
"guarantees" as a category of claim — that a *word-blocklist* could catch
this one example is exactly the trap: it is defeated by the next
adversarial phrasing that doesn't use that word. The only boundary that
holds regardless of phrasing is admitting zero characters of
model-authored free text into `.text` at all.
`test_response_with_extra_free_text_line_alongside_valid_citation_is_rejected`
proves even an innocuous-looking, digit-free, claim-unrelated line
("Here is what's confirmed:") sitting alongside an otherwise-valid
citation still gets the whole response rejected — the boundary is "no
free text", not "no *suspicious* free text".

### Layer 1 (unchanged): defensive re-filtering of the input
Exactly the same "never trust a caller blindly" principle already applied
twice this session for the identical reason — `app/planning/comparison.py`'s
`field_value_for()` (never surfaces a claim whose status isn't published,
or whose source is synthetic, even though a DB trigger is also supposed to
prevent that combination) and `app/api/eligibility.py`'s
`_criteria_from_claims` (re-filters to published rows itself rather than
trusting RLS visibility, because a reviewer's own RLS-scoped client can
legitimately SELECT drafts). This module does the same third check here:
even though the caller is *supposed* to only ever pass already-published
claims, `_grounded_claims` drops anything that is not
`ClaimStatus.published`, and separately drops anything backed by a
`SourceType.synthetic` source.

### Layer 3 (new): freshness/SLA staleness, not just publication status
Publication status alone does not mean "still trustworthy right now" — a
claim published years ago with a long-overdue `review_due_date` is stale,
and CLAUDE.md's "no record -> not verified" spirit extends to "a
badly-overdue record isn't a fresh 'verified' either." This module mirrors
(imports the constant from, and reproduces the exact comparison
expression of) `app/planning/comparison.py`'s `trust_label_for_claim`
freshness check (`DEFAULT_FRESHNESS_SLA_DAYS`, `as_of - verification_date`)
rather than inventing a second staleness rule. Chosen behaviour (documented
here since the task left this as a judgment call): if ANY claim selected
in an otherwise-valid response is stale as of `as_of`, the WHOLE response
downgrades from `answered` to `insufficient_information` — the same
all-or-nothing philosophy as a fabricated citation, because a response
built partly on a stale fact is not a full-confidence answer either.
Unlike every other rejection reason, `citations` IS populated in this one
case (each carrying the new `review_due_date`/`is_stale` fields) — the
point of adding staleness data to `Citation` at all is so a future caller
can see exactly *which* claim(s) blocked the answer and surface a
"these are due for recheck" message, rather than losing that information
behind a bare refusal the way a fabrication-rejection correctly does.
`test_stale_claim_citation_is_rejected_but_staleness_info_reaches_the_citation`
covers this.

## Status vocabulary — reused, not invented
Per CLAUDE.md/task instructions, this module does not invent new
user-facing wording. `AIAnswerStatus` reuses the exact two terms already
established elsewhere in this codebase for "we don't have enough
verified information to answer" style states:
- `not_available` mirrors `app.data.models.TrustLabel.not_available` —
  "no record exists at all". Used when, after the defensive re-filter,
  there is no usable claim to ground an answer on — the provider is never
  even called in this case (nothing to spend the budget on).
- `insufficient_information` mirrors
  `app.data.models.EligibilityOutcome.insufficient_information` — "we
  have some information, but not enough to give a definite answer, and
  an unknown must never be dressed up as a guess". Used when claims were
  available but no validated, fully-grounded response could be produced
  (the provider declined, its response failed the selection-format
  validation above, or every selected claim was stale) — the safe
  degrade, never a partial/edited-down version of the rejected text.
- `answered` is the only status that ever carries `.text` — a response
  that passed selection-format validation AND freshness in full, with
  every sentence in `.text` generated by this module's own code from a
  trusted Claim, never by the provider.

## What this module does NOT guarantee (be precise, not overclaiming)
- It does not judge *relevance* — a provider could select a real,
  fresh, correctly-sourced claim that does not actually answer the
  student's question. That produces a truthful-but-unhelpful sentence,
  not a fabricated one; out of scope for this module, which guarantees
  factual grounding, not relevance quality.
- It does not do PII redaction (no student-supplied free text reaches a
  route yet — noted forward-looking, not fixed here) or fix the
  in-process budget counter's theoretical race condition under multiple
  workers (Lite runs one worker process — noted forward-looking, not
  fixed here). Both were judged not-yet-exploitable since no route exists
  yet that would reach either.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any

from app.ai.adapter import AIProvider
from app.ai.budget import AIRequestBudget
from app.ai.schemas import AIAnswerStatus
from app.data.models import Claim, ClaimStatus, Source, SourceType
from app.planning.comparison import DEFAULT_FRESHNESS_SLA_DAYS

# One line of a valid response: "[<claim_id>]" and NOTHING else — no
# sentence, no value, no trailing punctuation. `claim_id`s in this
# codebase are UUID strings (app/data/models.py), so excluding `[` and
# `]` themselves is enough to make the match unambiguous without needing
# to know the exact id format. The `$` anchor (with `re.match`, which is
# implicitly anchored at the start) is what makes this a *whole-line*
# match — anything trailing the closing bracket fails it, which is
# exactly what blocks the "[claim-real] <fabricated sentence>" exploit
# this module's docstring documents.
_SELECTION_LINE = re.compile(r"^\[(?P<claim_id>[^\[\]]+)\]$")

# The exact token the prompt instructs the provider to return, verbatim
# and alone, when none of the supplied claims answer the question.
NOT_GROUNDED_TOKEN = "NOT_GROUNDED"


# AIAnswerStatus lives in app/ai/schemas.py (BCI-009/AI-1) as the single
# canonical definition — re-exported here so every existing import of
# `app.ai.grounding.AIAnswerStatus` keeps working unchanged. This module
# only ever assigns three of its six members (`answered`, `not_available`,
# `insufficient_information` — see the module docstring's "Status
# vocabulary" section for why); schemas.py's three extra members
# (`ai_unavailable`, `budget_exhausted`, `unsupported_template`) belong to
# the request/route layer, not this pure grounding module, and this file
# never constructs or compares against them. Two same-named enums briefly
# existed in this package (2026-09-22, see docs/DECISIONS.md) — this
# import is the reconciliation, not a new decision.


@dataclass(frozen=True)
class Citation:
    """One verified Claim a grounded answer's text actually relied on
    (or, for the staleness-rejection path only, a claim that a response
    tried to rely on but was blocked — see the module docstring's
    "Layer 3" section for why that one case still populates this)."""

    claim_id: str
    field: str
    value: str | int | float | bool | list[Any] | dict[str, Any] | None
    source_authority: str | None
    source_url: str | None
    verification_date: date
    review_due_date: date
    is_stale: bool


@dataclass(frozen=True)
class GroundedAnswer:
    """The result of `answer_question`.

    `text` is populated only when `status == AIAnswerStatus.answered`, and
    when it is, every sentence in it was generated by this module's own
    `_fact_sentence()` from a trusted Claim's own fields — never authored
    or echoed from provider output — which is the property this whole
    module exists to guarantee (see module docstring). `citations` is
    normally populated only alongside `answered` too, EXCEPT in the one
    staleness-rejection case documented in the module docstring, where it
    is deliberately still populated (with `is_stale=True`) so a future
    caller can identify which claim(s) blocked the answer.
    `rejection_reason` is never shown to a student; it is for logs/tests
    to see *why* an answer was withheld (a caller must never surface it
    as if it were an answer).
    """

    status: AIAnswerStatus
    text: str | None
    citations: tuple[Citation, ...] = field(default_factory=tuple)
    rejection_reason: str | None = None


def _grounded_claims(claims: list[Claim], sources_by_id: dict[str, Source]) -> list[Claim]:
    """Defensive re-filter — see the module docstring's "Layer 1".

    Never trust that every `Claim` in `claims` is actually safe to ground
    on, even though the caller is responsible for only ever passing
    already-published claims. Two independent checks, mirroring
    `app/planning/comparison.py`'s `trust_label_for_claim`:
    - `claim.status` must be `ClaimStatus.published` — draft, in_review
      and superseded claims are dropped even if present in the input.
    - the claim's source must not be `SourceType.synthetic` — a synthetic
      fixture must never be used as grounding material, even if (by a bug
      or a stale cache) it somehow carries `status=published`.
    A claim whose `source_id` cannot be resolved in `sources_by_id` is
    also dropped — no source to cite means nothing to verify against.

    Freshness/staleness is intentionally NOT checked here — a stale claim
    is still real, published, non-synthetic grounding material (unlike
    the three cases above); it is still offered to the provider, and
    staleness is instead checked in `_parse_and_validate`, after
    selection, so a stale-but-selected claim's `review_due_date`/
    `is_stale` can be surfaced on a `Citation` rather than silently
    disappearing (see the module docstring's "Layer 3").
    """
    grounded = []
    for claim in claims:
        if claim.status != ClaimStatus.published:
            continue
        source = sources_by_id.get(claim.source_id)
        if source is None:
            continue
        if source.source_type == SourceType.synthetic:
            continue
        grounded.append(claim)
    return grounded


def _build_prompt(question: str, claims: list[Claim], sources_by_id: dict[str, Source]) -> str:
    """Build the exact prompt sent to the provider.

    The "Verified facts" block below lists nothing but each claim's
    field, value, source authority and verification date — no other
    context, no system knowledge is invited in. The instructions ask the
    provider for exactly one thing: a bare `[<claim_id>]` selection line
    per relevant fact, and explicitly forbid anything else — no sentence,
    no restated value, no commentary of any kind. This is deliberately
    narrower than "please only use these facts and cite them" — the
    provider is never asked to compose prose at all, so there is nothing
    for `_parse_and_validate` to have to tell true from false (see the
    module docstring's "core safety mechanism").
    """
    lines = [
        "You are helping select which verified facts, if any, answer an "
        "Indian school student's career-pathway question. You do NOT write "
        "the answer yourself -- a separate system turns your selection into "
        "the actual answer text using only the verified data below. You must "
        "never author, restate, paraphrase or explain any fact, number, "
        "date, name or value yourself.",
        "",
        "For each fact below that helps answer the question, respond with "
        "exactly one line containing ONLY that fact's claim id in square "
        "brackets, in exactly this format and nothing else on the line:",
        "[<claim_id>]",
        "",
        "Do not add a sentence, value, explanation, or any punctuation to "
        "a citation line. Do not add any other line of any kind -- no "
        "introduction, no summary, no commentary. Your entire response "
        "must consist of nothing but citation lines in that exact format.",
        f"If NONE of the facts below answer the question, respond with "
        f"exactly the single word: {NOT_GROUNDED_TOKEN}",
        "",
        "Verified facts:",
    ]
    for claim in claims:
        source = sources_by_id.get(claim.source_id)
        authority = source.authority_name if source else "unknown source"
        lines.append(
            f"CLAIM {claim.id}: field={claim.field} value={claim.value!r} "
            f"source={authority} verified_on={claim.verification_date.isoformat()}"
        )
    lines.append("")
    lines.append(f"Student question: {question}")
    return "\n".join(lines)


def _fact_sentence(claim: Claim, source: Source | None) -> str:
    """The ONLY place a fact-bearing sentence is composed, anywhere in
    this module. Plain string substitution from an already
    defensively-filtered, trusted `Claim`'s own fields — never from
    provider output. This is what makes "no fabricated fact content in
    `.text`" true by construction: the provider's response is never
    consulted here at all, only the `claim`/`source` objects this module
    already trusts (see the module docstring's "core safety mechanism").
    """
    authority = source.authority_name if source else "an unspecified source"
    field_label = claim.field.replace("_", " ")
    if claim.value is None:
        return (
            f"According to {authority} (verified "
            f"{claim.verification_date.isoformat()}): no value is recorded "
            f"for {field_label}."
        )
    return (
        f"According to {authority} (verified {claim.verification_date.isoformat()}): "
        f"{field_label} is {claim.value}."
    )


def _is_stale(claim: Claim, *, as_of: date) -> bool:
    """Mirrors `app/planning/comparison.py`'s `trust_label_for_claim`
    freshness check exactly (same constant, same comparison) — see the
    module docstring's "Layer 3"."""
    return (as_of - claim.verification_date) > timedelta(days=DEFAULT_FRESHNESS_SLA_DAYS)


def _citation_for(claim: Claim, source: Source | None, *, as_of: date) -> Citation:
    return Citation(
        claim_id=claim.id,
        field=claim.field,
        value=claim.value,
        source_authority=source.authority_name if source else None,
        source_url=source.official_url if source else None,
        verification_date=claim.verification_date,
        review_due_date=claim.review_due_date,
        is_stale=_is_stale(claim, as_of=as_of),
    )


def _parse_and_validate(
    raw_response: str,
    grounded_claims_by_id: dict[str, Claim],
    sources_by_id: dict[str, Source],
    *,
    as_of: date,
) -> GroundedAnswer:
    """Mechanically reject any response that is not entirely a sequence
    of bare, in-context `[<claim_id>]` selection lines — see the module
    docstring's "core safety mechanism". All-or-nothing — a response is
    never trimmed down to "the lines that did validate," because a
    provider that fabricated (or even just free-texted) any part of a
    response has demonstrated it cannot be trusted for the rest of that
    same response either.

    On a fully valid selection, builds each sentence in the result via
    `_fact_sentence()` — never from anything the provider wrote — and
    then applies the freshness/SLA check (module docstring's "Layer 3"):
    if any selected claim is stale, the whole response downgrades to
    `insufficient_information` even though the selection itself was
    otherwise valid.
    """
    stripped = raw_response.strip()
    if not stripped:
        return GroundedAnswer(
            status=AIAnswerStatus.insufficient_information,
            text=None,
            rejection_reason="Provider returned an empty response.",
        )
    if stripped == NOT_GROUNDED_TOKEN:
        return GroundedAnswer(
            status=AIAnswerStatus.insufficient_information,
            text=None,
            rejection_reason="Provider reported none of the given claims answer the question.",
        )

    selected_ids: list[str] = []
    seen_claim_ids: set[str] = set()

    for raw_line in stripped.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = _SELECTION_LINE.match(line)
        if match is None:
            return GroundedAnswer(
                status=AIAnswerStatus.insufficient_information,
                text=None,
                rejection_reason=(
                    "Response line was not a bare '[claim_id]' selection line "
                    "(no other text is permitted on a citation line, and no "
                    "other kind of line is permitted at all), so the whole "
                    f"response was rejected: {line!r}"
                ),
            )
        claim_id = match.group("claim_id").strip()
        if claim_id not in grounded_claims_by_id:
            return GroundedAnswer(
                status=AIAnswerStatus.insufficient_information,
                text=None,
                rejection_reason=(
                    f"Response selected claim_id {claim_id!r}, which was not among "
                    "the claims supplied as grounding context for this question — "
                    "rejected as an out-of-context/fabricated selection."
                ),
            )
        if claim_id not in seen_claim_ids:
            seen_claim_ids.add(claim_id)
            selected_ids.append(claim_id)

    if not selected_ids:
        return GroundedAnswer(
            status=AIAnswerStatus.insufficient_information,
            text=None,
            rejection_reason="Response contained no valid selection lines.",
        )

    citations = [
        _citation_for(
            grounded_claims_by_id[claim_id],
            sources_by_id.get(grounded_claims_by_id[claim_id].source_id),
            as_of=as_of,
        )
        for claim_id in selected_ids
    ]
    stale_citations = [c for c in citations if c.is_stale]
    if stale_citations:
        stale_ids = ", ".join(c.claim_id for c in stale_citations)
        return GroundedAnswer(
            status=AIAnswerStatus.insufficient_information,
            text=None,
            citations=tuple(citations),
            rejection_reason=(
                f"Response relied on claim(s) {stale_ids} whose freshness SLA "
                f"({DEFAULT_FRESHNESS_SLA_DAYS} days, mirroring "
                "app/planning/comparison.py's trust_label_for_claim) has lapsed "
                f"as of {as_of.isoformat()} — a stale claim cannot produce a "
                "full-confidence answer. See each returned Citation's "
                "`is_stale`/`review_due_date` for which claim(s) blocked this."
            ),
        )

    sentences = [
        _fact_sentence(
            grounded_claims_by_id[claim_id],
            sources_by_id.get(grounded_claims_by_id[claim_id].source_id),
        )
        for claim_id in selected_ids
    ]

    return GroundedAnswer(
        status=AIAnswerStatus.answered,
        text="\n".join(sentences),
        citations=tuple(citations),
    )


def answer_question(
    question: str,
    claims: list[Claim],
    sources_by_id: dict[str, Source],
    *,
    provider: AIProvider,
    budget: AIRequestBudget,
    as_of: date | None = None,
) -> GroundedAnswer:
    """Answer `question` using only `claims` as grounding material.

    `claims` is expected to already be published/verified context fetched
    by the caller (a future route) — this function does not fetch
    anything itself, and re-filters defensively regardless (see
    `_grounded_claims`).

    `as_of` is the date staleness is measured against (module docstring's
    "Layer 3"); defaults to `date.today()`, mirroring
    `app/planning/comparison.py`'s own `as_of` convention. Tests pass an
    explicit fixed date for determinism.

    Order of operations, all deliberate:
    1. Re-filter to genuinely-grounded claims. If none remain, return
       `not_available` WITHOUT calling the provider or touching the
       budget — there is nothing to answer from, so there is nothing to
       spend on.
    2. Build the selection-only prompt from (only) those claims.
    3. Reserve one call against `budget`. If the daily cap is already
       exhausted, `budget.reserve()` raises `AIBudgetExceededError` and
       this function does not call the provider — that exception
       propagates to the caller unchanged (a clear failure, not a
       silent `not_available`, so a caller can tell "no verified
       information" apart from "the AI feature is out of budget today").
    4. Call the provider, then run its raw response through
       `_parse_and_validate`, which is the only path by which `status`
       can become `answered` — and which is the only place any
       fact-bearing sentence is ever composed, always from the module's
       own trusted claim data, never from the provider's text (module
       docstring).
    """
    grounded = _grounded_claims(claims, sources_by_id)
    if not grounded:
        return GroundedAnswer(
            status=AIAnswerStatus.not_available,
            text=None,
            rejection_reason="No published, non-synthetic claims were available for this question.",
        )

    grounded_claims_by_id = {claim.id: claim for claim in grounded}
    prompt = _build_prompt(question, grounded, sources_by_id)

    budget.reserve()  # raises AIBudgetExceededError; never caught here — see docstring.
    raw_response = provider.generate(prompt)

    resolved_as_of = as_of if as_of is not None else date.today()
    return _parse_and_validate(
        raw_response, grounded_claims_by_id, sources_by_id, as_of=resolved_as_of
    )
