"""The guards `app/ai/pipeline.py`'s two-pass runner is built on: strict
whole-response line-format validation for each pass, the traceability
check that stands in for an outbound-payload call, code-only sentence/
citation generation, the banned-phrase build/test-time check
(`assert_no_banned_phrases`), and its independent runtime companion
(`scan_generated_sentences`, BCI-027) that re-checks the sentences a
pipeline actually generates from a published record's own value, per
request, without raising.

## Why this module exists rather than importing from `app/ai/grounding.py`

`app/ai/grounding.py`'s `_parse_and_validate`, `_fact_sentence` and
`_citation_for` implement exactly the properties this pipeline needs
(whole-response all-or-nothing line validation; sentences generated by
code from a trusted object's own fields, never by the provider) — but
every one of them is written against `app.data.models.Claim`/`Source`,
not `app.ai.retrieval.RetrievedRecord` (this pipeline's own input shape,
which does not carry a `verification_date` at all — only a pre-computed
`is_stale` boolean). `grounding.py` is on this card's forbidden-files
list, and that list is explicit about the resolution: "if you need to
extract a shared helper, add it as a new function in grounding.py is NOT
allowed from this card; instead add the shared helper in your own owned
files ... even if that means a small amount of duplication you document
rather than editing a file you don't own." This module is that
documented duplication — the same PATTERN (regex shape, all-or-nothing
rejection, code-only sentence assembly) reproduced against
`RetrievedRecord`'s narrower shape, not a second, subtly different
design. Every function below says explicitly which `grounding.py`
function it mirrors and exactly how the input shape forced a difference.

## The verification-pass format (`parse_verification_response`)

Has no equivalent in `grounding.py` at all — a single-pass module has no
second, adversarial pass to validate. This format (`YES <id>` / `NO
<id>`, one per line) and its all-or-nothing rejection rule are this
card's own, described in `tasks/BCI-015.md` step 9.
"""

from __future__ import annotations

import re
from collections.abc import Collection, Mapping, Sequence
from typing import Any, Final

from app.ai.grounding import NOT_GROUNDED_TOKEN
from app.ai.retrieval import RetrievedRecord
from app.ai.schemas import OutboundPayload, find_banned_phrases

# One line of a valid PASS-ONE (selection) response: "[<record_id>]" and
# NOTHING else. Deliberately the same pattern
# `app/ai/grounding.py`'s own `_SELECTION_LINE` uses (see module
# docstring) — duplicated, not imported, because that name is private to
# a file this card must not edit.
_SELECTION_LINE: Final[re.Pattern[str]] = re.compile(r"^\[(?P<record_id>[^\[\]]+)\]$")

# One line of a valid PASS-TWO (verification) response: "YES <id>" or
# "NO <id>", exactly, and nothing else. This card's own format — no
# `grounding.py` equivalent (see module docstring).
_VERIFICATION_LINE: Final[re.Pattern[str]] = re.compile(
    r"^(?P<verdict>YES|NO) (?P<record_id>[^\s\[\]]+)$"
)


class UntraceableRecordValueError(RuntimeError):
    """Raised when a value this pipeline is about to embed in a prompt
    does not trace back to the retrieved record set it claims to come
    from.

    This can only happen because of a bug in this pipeline's OWN prompt
    construction — there is no student free text anywhere in Phase 1a
    (this card's Rule 3) for anything to smuggle a mismatched value in
    at runtime. Deliberately never caught anywhere in `app/ai/pipeline.py`:
    a bug here must fail loudly (an unhandled exception, caught by a
    test) rather than silently drop the offending value and keep going,
    per this card's own step 5 instruction.
    """


def _records_map(records: Sequence[RetrievedRecord]) -> dict[str, dict[str, str]]:
    """`RetrievedRecord`s -> the `record_id -> {field: value}` shape
    `app.ai.schemas.OutboundPayload.from_records` requires. Every
    `RetrievedRecord.value` is coerced to `str` here (the outbound
    payload's own value slots are strings, `app/ai/schemas.py`'s
    `OutboundPayload.record_values: dict[str, str]`) — this is a type
    coercion, not a content transformation: `_check_value_shape` in
    `schemas.py` re-validates the coerced string (non-blank, bounded,
    single-line) regardless."""
    return {record.id: {record.field: str(record.value)} for record in records}


def build_outbound_payload(
    template_id: str, records: Sequence[RetrievedRecord], *, lang: str
) -> tuple[OutboundPayload, dict[str, dict[str, str]]]:
    """Build the `OutboundPayload` representation of `records` — this
    card's step 5. Returns the payload alongside the exact `records_map`
    it was built from, so a caller can immediately run
    `assert_payload_traceable` against the same map (see that function).

    No network call happens anywhere in this module or `app/ai/pipeline.py`
    — `AIProvider.generate()` takes a prompt string, not an
    `OutboundPayload`. This function exists purely so step 5's
    traceability invariant is checked in code, every time, rather than
    only asserted in a docstring.
    """
    records_map = _records_map(records)
    payload = OutboundPayload.from_records(template_id=template_id, records=records_map, lang=lang)
    return payload, records_map


def assert_payload_traceable(
    payload: OutboundPayload, records_map: Mapping[str, Mapping[str, str]]
) -> None:
    """Raise `UntraceableRecordValueError` if any value on `payload` does
    not trace back to `records_map` — `OutboundPayload.untraceable_values`
    (already merged, `app/ai/schemas.py`) does the actual check; this is
    just the "raise loudly rather than silently drop" wrapper this card's
    step 5 asks for.

    Built via `OutboundPayload.from_records(records=records_map, ...)`
    (see `build_outbound_payload` above), `payload` is untraceable-free
    *by construction* against that same `records_map`
    (`OutboundPayload.from_records`'s own docstring) — so under normal
    pipeline operation this never raises. It exists as a named,
    independently-testable invariant rather than an implicit assumption,
    so a future edit that builds the payload from one record set and
    checks it against a different one is a caught bug, not a silent
    drop. `tests/unit/test_ai_pipeline.py` proves the raise path directly
    by constructing exactly that mismatch.
    """
    untraceable = payload.untraceable_values(records_map)
    if untraceable:
        raise UntraceableRecordValueError(
            f"record_values keys not traceable to the retrieved record set: {untraceable!r}"
        )


def parse_selection_response(raw: str, valid_ids: Collection[str]) -> tuple[str, ...]:
    """All-or-nothing PASS-ONE parser — mirrors
    `app/ai/grounding.py`'s `_parse_and_validate` selection-line rules
    exactly (same whole-line `[<id>]` regex shape, same "any bad line
    rejects everything" rule, same duplicate-line tolerance), retargeted
    to a plain `valid_ids` collection instead of a `dict[str, Claim]`
    (see module docstring for why `grounding.py`'s own function is not
    called directly).

    Returns an empty tuple for every invalid case — an empty/blank
    response, the literal `NOT_GROUNDED` token, any line that is not an
    exact `[<record_id>]` match, or any id not in `valid_ids` — the whole
    response is discarded, never trimmed down to "the lines that did
    validate" (same all-or-nothing philosophy `grounding.py`'s own
    docstring documents). The caller does not need to know WHY a response
    produced no ids, only that it did.

    On success, returns the selected ids in first-seen order, with
    duplicates removed — mirrors `grounding.py`'s own
    `test_response_with_duplicate_citation_lines_is_deduplicated`
    precedent: a repeated citation of the same id is not itself a format
    violation.
    """
    stripped = raw.strip()
    if not stripped or stripped == NOT_GROUNDED_TOKEN:
        return ()

    selected: list[str] = []
    seen: set[str] = set()
    for raw_line in stripped.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = _SELECTION_LINE.match(line)
        if match is None:
            return ()
        record_id = match.group("record_id").strip()
        if record_id not in valid_ids:
            return ()
        if record_id not in seen:
            seen.add(record_id)
            selected.append(record_id)
    return tuple(selected)


def parse_verification_response(
    raw: str, allowed_ids: Collection[str]
) -> tuple[str, ...] | None:
    """All-or-nothing PASS-TWO parser — this card's own format, no
    `grounding.py` equivalent (see module docstring).

    Every non-blank line must be an exact `YES <id>` or `NO <id>` match,
    and every named id must be one of `allowed_ids` (the ids pass one
    actually selected) — any other line, or any id outside that set,
    invalidates the WHOLE response (this card's step 9: "Anything outside
    that format invalidates the whole response"). Returns `None` for any
    such violation, so a caller can tell "the response was malformed"
    apart from "the response was well-formed but confirmed nothing" (the
    latter returns an empty tuple, not `None` — see below).

    A record id that appears twice with the SAME verdict is tolerated
    (same duplicate-line precedent `parse_selection_response` follows); a
    record id that appears with BOTH a `YES` and a `NO` verdict is
    self-contradictory and is treated as a format violation (`None`) —
    a response that disagrees with itself about the same id cannot be
    trusted for any of it.

    On success, returns the ids confirmed `YES`, in first-seen order.
    Every one of these ids is guaranteed to be in `allowed_ids` (checked
    above), so the result is a subset of pass one's own selection by
    construction — `app/ai/pipeline.py` still re-derives the final
    intersection explicitly rather than relying on this alone, as a
    second, defensive check of the same invariant `app.ai.schemas.Answer`
    itself enforces (`verification_ids` must be a subset of
    `selection_ids`).
    """
    stripped = raw.strip()
    if not stripped:
        return ()

    verdicts: dict[str, str] = {}
    for raw_line in stripped.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = _VERIFICATION_LINE.match(line)
        if match is None:
            return None
        record_id = match.group("record_id").strip()
        verdict = match.group("verdict")
        if record_id not in allowed_ids:
            return None
        if record_id in verdicts and verdicts[record_id] != verdict:
            return None
        verdicts[record_id] = verdict
    return tuple(record_id for record_id, verdict in verdicts.items() if verdict == "YES")


def fact_sentence_for_record(record: RetrievedRecord) -> str:
    """The ONLY place a fact-bearing sentence is composed for this
    pipeline. Plain string substitution from an already trust-checked
    `RetrievedRecord`'s own fields — never from anything a provider
    returned. Mirrors `app/ai/grounding.py`'s `_fact_sentence` PATTERN
    (same phrasing style, same `field.replace("_", " ")` label
    derivation, same "no value recorded" branch) but NOT its exact output
    text: `RetrievedRecord` (`app/ai/retrieval.py`) carries no
    `verification_date` field at all (only the pre-derived boolean
    `is_stale`), so the "(verified <date>)" clause `grounding.py`'s
    template includes cannot be reproduced here — reported as the exact
    coupling problem this card's stop-conditions ask for, not silently
    smoothed over. By the time this is called (`app/ai/pipeline.py` step
    11, after step 10's freshness check), every surviving record is
    already known-fresh, so the omission never hides a staleness caveat.
    """
    authority = record.source_authority or "an unspecified source"
    field_label = record.field.replace("_", " ")
    if record.value is None:
        return f"According to {authority}: no value is recorded for {field_label}."
    return f"According to {authority}: {field_label} is {record.value}."


def citation_for_record(record: RetrievedRecord) -> dict[str, Any]:
    """A plain-data citation for `record` — every field copied straight
    from the already trust-checked `RetrievedRecord`, never from provider
    output. `app.ai.schemas.Answer.citations` is typed `list[dict[str,
    Any]]` (not a dataclass), so this returns exactly that shape rather
    than inventing a new frozen type this module would then have to
    justify keeping in sync with `grounding.py`'s own `Citation`."""
    return {
        "record_id": record.id,
        "field": record.field,
        "value": record.value,
        "source_authority": record.source_authority,
        "source_url": record.source_url,
        "is_stale": record.is_stale,
    }


def scan_generated_sentences(sentences: Sequence[str]) -> tuple[str, ...]:
    """Runtime companion to `assert_no_banned_phrases` below (BCI-027) —
    scans sentences a pipeline is about to render to a student, never
    fixed, code-authored strings.

    `assert_no_banned_phrases`'s contract is "raise immediately, this is
    a build-time bug" — correct for `app.ai.prompts.TEMPLATE_REGISTRY`'s
    fixed labels, wrong here: a real request must never crash on this, it
    must degrade gracefully, exactly like every other failure mode
    `app/ai/pipeline.py`'s `answer()` and `app/ai/what_changed.py`'s
    `answer_what_changed()` already have (an unsupported template, a
    provider timeout, a stale record — none of those raise out of either
    pipeline either). So this function is pure and NEVER raises: it only
    reports which `BANNED_PHRASES` (`app/ai/schemas.py`) entries were
    found, in `find_banned_phrases` order, deduplicated across every
    sentence checked. A caller only needs to know THAT a hit occurred, in
    order to downgrade the whole answer — never which single sentence,
    since this pipeline's own "reject whole, never partial" design
    principle (module docstring) applies here exactly as it does to every
    other validation step.

    Why this exists: `app.ai.guards.fact_sentence_for_record`'s own
    docstring already establishes that no character the provider wrote
    ever reaches a rendered sentence — every sentence is built by code
    from an already-PUBLISHED, reviewer-approved record's own `.value`.
    But that value itself was typed by a human at review time, and
    nothing previously re-checked it for hedge/guarantee/ranking language
    before rendering — a content error at review time (not an AI
    hallucination) would previously have reached a student completely
    unscanned. Maker-checker review is supposed to catch this at source;
    this is the same mechanical backstop `BANNED_PHRASES` already
    provides everywhere else it is checked (fixed strings via
    `assert_no_banned_phrases`, the eval set's own calibration fixtures),
    finally wired to the one place — runtime-generated content — it was
    previously documented as covering but never actually was.

    Callers: `app/ai/pipeline.py`'s `answer()` (over `Answer.sentences`,
    between step 11's sentence generation and step 13's final return) and
    `app/ai/what_changed.py`'s `answer_what_changed()` (over each
    `RenderedDiffLine.text`, its own equivalent final-render step) — both
    downgrade the WHOLE answer to `AIAnswerStatus.insufficient_information`
    on any non-empty result here, never redact a single sentence/line and
    keep the rest.
    """
    hits: list[str] = []
    for sentence in sentences:
        for phrase in find_banned_phrases(sentence):
            if phrase not in hits:
                hits.append(phrase)
    return tuple(hits)


def assert_no_banned_phrases(*texts: str) -> None:
    """Guard for this card's step 12: run `find_banned_phrases` (already
    merged, `app/ai/schemas.py`) over every FIXED, code-authored string
    this pipeline is about to render — never over provider output, since
    none ever reaches `Answer.sentences` (see `fact_sentence_for_record`'s
    docstring). A hit here means a future edit introduced hedge/guarantee
    language into a hardcoded string, so it raises immediately rather
    than degrading silently. `app/ai/prompts.py`'s `TEMPLATE_REGISTRY`
    labels are checked against this at import time (see that module) and
    `tests/unit/test_ai_pipeline.py` checks it again directly — "a hit
    here is a test failure, not a runtime path" (this card's step 12).
    """
    for text in texts:
        hits = find_banned_phrases(text)
        if hits:
            raise AssertionError(
                f"banned phrase(s) {hits!r} found in a fixed pipeline string: {text!r}"
            )
