"""A deterministic, fake `AIProvider` for tests — never a network call,
never non-deterministic, and clearly synthetic (CLAUDE.md: synthetic
fixtures must be unmistakably not the real thing).

Three response modes, chosen at construction, checked in this priority
order on every `.generate()` call (a scripted per-call failure always
wins, since a test that asked for a specific call to fail must never
silently get a normal response instead):

1. **A scripted failure for this call number** (`raise_on_call`, AI-3):
   see that method's docstring. Checked first, on every call, regardless
   of `responses`/`canned_response`.
2. **Sequenced (`responses=[...]`, AI-3)**: a list of responses, one per
   `.generate()` call in order — call 1 gets `responses[0]`, call 2 gets
   `responses[1]`, and so on. This is what a later card's two-pass
   pipeline needs: it calls `.generate()` twice per answer (selection,
   then verification) and a test must be able to control each call's
   response independently, e.g. `MockAIProvider(responses=["[claim-a]",
   "[claim-a]"])` for a selection pass followed by a verification pass
   that confirms the same id, or a mismatched pair to test the
   verification-shrinks-selection path. Calling `.generate()` more times
   than `responses` has entries is a test-authoring bug, not a provider
   behaviour to model, so it raises `AssertionError` rather than looping
   or returning something arbitrary.
3. **Canned (`canned_response=<str>`, pre-existing)**: returns exactly
   the given string on every call, ignoring the prompt entirely. This is
   how a test constructs an *adversarial* response — e.g. a line citing a
   `claim_id` that was never in the prompt, a citation line with extra
   text smuggled onto it, or a stray free-text line alongside an
   otherwise-valid selection — to prove `app/ai/grounding.py`'s
   validation actually rejects it, rather than merely asserting the happy
   path.
4. **Grounded echo (default, everything above is `None`, pre-existing)**:
   parses the `CLAIM <id>: ...` lines `app/ai/grounding.py`'s
   `_build_prompt` embeds in the prompt it is given, and echoes back
   exactly one bare `[<claim_id>]` selection line per claim found — i.e.
   a response that *should* pass `grounding._parse_and_validate` in full
   under the selection-only contract (see `app/ai/grounding.py`'s module
   docstring). This lets tests exercise the real parsing/validation/
   sentence-generation path end-to-end on a legitimate response, rather
   than only ever testing the rejection path. Note this mode never writes
   any fact-bearing text itself — under the contract there is nothing for
   it to write; every sentence in the resulting `GroundedAnswer.text` is
   generated by `grounding._fact_sentence()` from the claim's own data,
   not by this mock.

Every existing test that only ever set `canned_response`/relied on the
echo default keeps working unchanged — modes 1 and 2 are strictly
additive and inert unless a test opts into them.

`calls` records every prompt this instance was asked to `generate()` a
response for (recorded before any scripted failure is raised, since the
call itself genuinely happened — only its outcome is being scripted), so
a test can also assert something about what was actually sent to the
provider (e.g. that a filtered-out claim's value never appears in the
prompt text at all, or that a second/verification-pass prompt differs
from the first).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from app.ai.grounding import NOT_GROUNDED_TOKEN

_CLAIM_ID_IN_PROMPT = re.compile(r"^CLAIM (?P<claim_id>\S+):", re.MULTILINE)


@dataclass
class MockAIProvider:
    """Deterministic `AIProvider` implementation for tests. See module
    docstring for the four response modes and their priority order."""

    canned_response: str | None = None
    #: Sequenced responses, one per `.generate()` call in order. `None`
    #: (the default) leaves this mode inactive — see module docstring
    #: mode 2.
    responses: list[str] | None = None
    calls: list[str] = field(default_factory=list)
    #: 1-indexed call number -> the error to raise on that call, set via
    #: `raise_on_call`. Not a constructor parameter (a test scripts this
    #: after construction, via the method below) — kept out of `repr` so
    #: a failed-assertion printout of a `MockAIProvider` stays readable.
    _raise_on_call: dict[int, BaseException | type[BaseException]] = field(
        default_factory=dict, init=False, repr=False
    )

    def raise_on_call(self, n: int, error: BaseException | type[BaseException]) -> None:
        """Script `.generate()`'s `n`-th call (1-indexed) to raise
        `error` instead of returning text.

        `error` may be an already-constructed exception instance (so a
        test controls its exact message) or an exception class (in which
        case a generic message is used) — either way it is one of
        `app/ai/schemas.py`'s typed provider errors in the tests that use
        this, e.g. `provider.raise_on_call(2, AIProviderTimeout("..."))`
        to make a two-pass pipeline's *verification* call (the 2nd) fail
        while its selection call (the 1st) still succeeds normally.

        Checked before `responses`/`canned_response`/the echo default on
        every `.generate()` call — see the module docstring's priority
        order. A call number with nothing scripted falls through to
        whichever of the other modes is active, unaffected.
        """
        if n < 1:
            raise ValueError(f"call number must be >= 1 (got {n})")
        self._raise_on_call[n] = error

    def generate(self, prompt: str) -> str:
        self.calls.append(prompt)
        call_number = len(self.calls)

        scripted_error = self._raise_on_call.get(call_number)
        if scripted_error is not None:
            if isinstance(scripted_error, BaseException):
                raise scripted_error
            raise scripted_error(
                f"MockAIProvider: scripted failure on generate() call {call_number}."
            )

        if self.responses is not None:
            index = call_number - 1
            if index >= len(self.responses):
                raise AssertionError(
                    f"MockAIProvider.responses has {len(self.responses)} scripted "
                    f"response(s), but generate() was called a {call_number}th "
                    "time -- script one response per expected call (or use "
                    "raise_on_call for a call that should fail instead of return "
                    "text)."
                )
            return self.responses[index]

        if self.canned_response is not None:
            return self.canned_response
        return self._echo_claims_from_prompt(prompt)

    @staticmethod
    def _echo_claims_from_prompt(prompt: str) -> str:
        claim_ids = _CLAIM_ID_IN_PROMPT.findall(prompt)
        if not claim_ids:
            # Mirrors what a well-behaved real provider should do when the
            # prompt's "Verified facts" section is empty — though
            # app/ai/grounding.py never actually calls the provider in
            # that case, this keeps the mock correct standalone too.
            return NOT_GROUNDED_TOKEN
        return "\n".join(f"[{claim_id}]" for claim_id in claim_ids)
