"""A deterministic, fake `AIProvider` for tests — never a network call,
never non-deterministic, and clearly synthetic (CLAUDE.md: synthetic
fixtures must be unmistakably not the real thing).

Two modes, chosen at construction:

- **Grounded echo (default, `canned_response=None`)**: parses the
  `CLAIM <id>: ...` lines `app/ai/grounding.py`'s `_build_prompt` embeds
  in the prompt it is given, and echoes back exactly one bare
  `[<claim_id>]` selection line per claim found — i.e. a response that
  *should* pass `grounding._parse_and_validate` in full under the new
  selection-only contract (see `app/ai/grounding.py`'s module docstring).
  This lets tests exercise the real parsing/validation/sentence-generation
  path end-to-end on a legitimate response, rather than only ever testing
  the rejection path. Note this mode never writes any fact-bearing text
  itself — under the new contract there is nothing for it to write; every
  sentence in the resulting `GroundedAnswer.text` is generated by
  `grounding._fact_sentence()` from the claim's own data, not by this mock.

- **Canned (`canned_response=<str>`)**: returns exactly the given string,
  ignoring the prompt entirely. This is how a test constructs an
  *adversarial* response — e.g. a line citing a `claim_id` that was never
  in the prompt, a citation line with extra text smuggled onto it, or a
  stray free-text line alongside an otherwise-valid selection — to prove
  `app/ai/grounding.py`'s validation actually rejects it, rather than
  merely asserting the happy path.

`calls` records every prompt this instance was asked to `generate()` a
response for, so a test can also assert something about what was
actually sent to the provider (e.g. that a filtered-out claim's value
never appears in the prompt text at all).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from app.ai.grounding import NOT_GROUNDED_TOKEN

_CLAIM_ID_IN_PROMPT = re.compile(r"^CLAIM (?P<claim_id>\S+):", re.MULTILINE)


@dataclass
class MockAIProvider:
    """Deterministic `AIProvider` implementation for tests. See module
    docstring for the two modes."""

    canned_response: str | None = None
    calls: list[str] = field(default_factory=list)

    def generate(self, prompt: str) -> str:
        self.calls.append(prompt)
        if self.canned_response is not None:
            return self.canned_response
        return self._echo_claims_from_prompt(prompt)

    @staticmethod
    def _echo_claims_from_prompt(prompt: str) -> str:
        claim_ids = _CLAIM_ID_IN_PROMPT.findall(prompt)
        if not claim_ids:
            # Mirrors what a well-behaved real provider should do when the
            # prompt's "Verified facts" section is empty — though
            # app/ai/grounding.py never actually calls the provider in
            # that case, this keeps the mock correct standalone too.
            return NOT_GROUNDED_TOKEN
        return "\n".join(f"[{claim_id}]" for claim_id in claim_ids)
